jobs:
  dist:
    docker:
    - auth:
        password: $DOCKER_PASSWORD
        username: $DOCKER_USERNAME
      image: circleci/golang:1.11
    steps:
    - checkout
    - run:
        command: 'sudo make -f Makefile.tools nfpm-debian rpmbuild-debian

          '
        name: Install nfpm, rpmbuild
    - run:
        command: 'make -f Makefile.release dist

          '
        name: Make distributables
    - persist_to_workspace:
        paths:
        - dist/*
        root: .
    working_directory: /go/src/github.com/segmentio/chamber
  publish-github:
    docker:
    - auth:
        password: $DOCKER_PASSWORD
        username: $DOCKER_USERNAME
      image: circleci/golang:1.11
    steps:
    - checkout
    - attach_workspace:
        at: .
    - run:
        command: 'make -f Makefile.tools github-release

          '
        name: Install tools
    - run:
        command: 'make -f Makefile.release publish-github

          '
        name: Release
    working_directory: /go/src/github.com/segmentio/chamber
  publish-packagecloud:
    docker:
    - auth:
        password: $DOCKER_PASSWORD
        username: $DOCKER_USERNAME
      image: circleci/golang:1.11
    steps:
    - checkout
    - attach_workspace:
        at: .
    - run:
        command: "# this is all for package_cloud :/\nsudo apt update -q \nsudo apt\
          \ install -yq ruby ruby-dev build-essential\n# fixes https://askubuntu.com/questions/872399/error-failed-to-build-gem-native-extension-when-trying-to-download-rubocop\n\
          sudo gem install rake\nsudo make -f Makefile.tools package_cloud\n"
        name: Install tools
    - run:
        command: 'make -f Makefile.release publish-packagecloud

          '
        name: Release
    working_directory: /go/src/github.com/segmentio/chamber
  test:
    docker:
    - auth:
        password: $DOCKER_PASSWORD
        username: $DOCKER_USERNAME
      image: circleci/golang:1.11
    steps:
    - checkout
    - run:
        command: 'make test

          '
        name: Test
    working_directory: /go/src/github.com/segmentio/chamber
  test-install-golang-1.11-GOMODULE-on:
    docker:
    - auth:
        password: $DOCKER_PASSWORD
        username: $DOCKER_USERNAME
      image: circleci/golang:1.11
    steps:
    - checkout
    - run:
        command: 'GO111MODULE=on go get -v . && chamber version

          '
        name: Test go get install on golang 1.11 GO111MODULE=on
    working_directory: /go/src/github.com/segmentio/chamber
  test-install-golang-current:
    docker:
    - auth:
        password: $DOCKER_PASSWORD
        username: $DOCKER_USERNAME
      image: circleci/golang:1.11
    steps:
    - checkout
    - run:
        command: 'go get -v . && chamber version

          '
        name: Test go get install on current golang release
    working_directory: /go/src/github.com/segmentio/chamber
  test-install-golang-prev:
    docker:
    - auth:
        password: $DOCKER_PASSWORD
        username: $DOCKER_USERNAME
      image: circleci/golang:1.10
    steps:
    - checkout
    - run:
        command: 'go get -v . && chamber version

          '
        name: Test install golang (previous release)
    working_directory: /go/src/github.com/segmentio/chamber
version: 2
workflows:
  test-dist-publish:
    jobs:
    - test:
        context:
        - org-global
    - test-install-golang-prev:
        context:
        - org-global
    - test-install-golang-current:
        context:
        - org-global
    - test-install-golang-1.11-GOMODULE-on:
        context:
        - org-global
    - dist:
        filters:
          tags:
            only: /.*/
    - publish-packagecloud:
        context: packagecloud
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /v[0-9]+(\.[0-9]+)*(-[a-zA-Z0-9-]+)?/
        requires:
        - dist
    - publish-github:
        context: github-segmentcircle-oss-release
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /v[0-9]+(\.[0-9]+)*(-[a-zA-Z0-9-]+)?/
        requires:
        - dist
  version: 2
